"""add_approval_status_to_users

Revision ID: f4aa1f1ed399
Revises: f4de7425edc5
Create Date: 2025-09-10 11:24:43.869877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4aa1f1ed399'
down_revision = 'f4de7425edc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
    
    # Update existing records to have APPROVED status (for existing users)
    op.execute("UPDATE users SET approval_status = 'APPROVED' WHERE approval_status IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('approval_status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
